name: drone_env

env:
  num_agents: 1

policy:
  drone_policy:
    model: FullyConnected
    # Observation space is 10:
    # 3 (Acc Body) + 3 (Rates) + 4 (Target Cmds)
    # Action space is 4
    hidden_dims: [128, 128]

trainer:
  num_envs: 1024       # Parallel environments on GPU
  episode_length: 100
  training_iterations: 1000
  num_gpus: 1

algorithm:
  name: PPO
  gamma: 0.99
  lr: 0.001
  clip_param: 0.2
  vf_loss_coeff: 0.5
  entropy_coeff: 0.01
